RK-258: created FraudReportStatus; changed DAL indices; made the remo…
hmrc/tax-fraud-reporting pull request #11
Opened 2022-01-07 11:23 UTC by ModisAtHMRC

…ve method check status before deletion

2022-01-09 22:16 UTC, shinealex33 approved these changes
Nice work Mod. LGTM

2022-01-11 10:43 UTC, wolfendale requested changes

2022-01-11 10:50 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreporting/controllers/FraudReportController.scala
> +          BadRequest(Json parse """{"errors": ["Missing X-Correlation-ID header"]}""")
Thought parsing is more legible but I'll change it back.

2022-01-11 10:52 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatus.scala
> +  implicit val writes: Writes[FraudReportStatus] = Writes(status => JsString(status.toString))
For that, should I just manually write out a list of expected strings and test that each enum value converts to them?

2022-01-11 11:22 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatus.scala
> +  implicit val writes: Writes[FraudReportStatus] = Writes(status => JsString(status.toString))
Yup, and a for the reads there'd be a failure case too

2022-01-11 11:24 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/controllers/FraudReportController.scala
> +          BadRequest(Json parse """{"errors": ["Missing X-Correlation-ID header"]}""")
Generally it's good practice to not have to parse a static string, in terms of readability personally I prefer to think about maintainability over readability. The AST syntax will only allow you to create valid json, with a string someone could very easily break it in a non-obvious way that we could have caught at compile time. Also you won't get any IDE support for a string literal with json in it, but you will when building up the AST.

2022-01-11 14:44 UTC, wolfendale requested changes

2022-01-11 14:44 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +  private val expectedStrings = "Received,Sent,Processed,Failed" split ','
Why split this instead of just using a collection?

2022-01-11 14:44 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +      assert(jsResult.isError)
You need to check that the error is the one that you expect

2022-01-11 14:44 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +      assert(jsResult.isError)
You need to check that the error is the one that you expect

2022-01-11 14:44 UTC, wolfendale commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +  }
You need tests to show that the correct strings can be read to the correct values

2022-01-11 14:47 UTC, ModisAtHMRC commented on app/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatus.scala
> +    case JsString(value) =>
Wrote a couple for invalid cases. The valid case is covered by integration tests.

2022-01-11 14:49 UTC, ModisAtHMRC commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +  private val expectedStrings = "Received,Sent,Processed,Failed" split ','
Ah, it's just a pattern I got used to in some front end work which helped with readability. I'll change it a `List`.

2022-01-11 15:08 UTC, ModisAtHMRC commented on test/uk/gov/hmrc/taxfraudreporting/models/FraudReportStatusSpec.scala
> +      assert(jsResult.isError)
OK, created new `FraudReportStatusJsError` enum in order have the type checker get in on this.

2022-01-11 15:52 UTC, merged