RK-253: Call SDES API to notify XML file is ready for collection
hmrc/tax-fraud-reporting pull request #14
Opened 2022-02-21 07:56 UTC by kiran-hmrc

* SDES notification call
* Update FraudRepository with correlation id post SDES notification

2022-02-21 16:20 UTC, wolfendale requested changes

2022-02-21 16:20 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +  private val objectStoreLocationPrefix: String = s"$fileLocationBaseUrl/object-store/object/ris-kana/"
We should make the path configurable. We may need to change it when testing our integrations

2022-02-21 16:20 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +  private def notifySDES(correlationID: UUID, fileName: String, objWithSummary: ObjectSummaryWithMd5): Unit = {
Should this actually be a `Future[Unit]` so that we can map off of it and check whether it's failed?

2022-02-21 16:20 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +        logger.error(s"Error in notifying SDES about file :: $fileName correlationId:: $correlationID.", exception)
This will be logged twice, we should decide to log it in a single place

2022-02-21 16:20 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/services/SDESService.scala
> +              s"Received a non 204 status from SDES when notified about file :: ${fileNotifyRequest.file.name}  with correlationId::${fileNotifyRequest.audit.correlationID}. Status: $status, body: ${
This will be logged twice as stated above

2022-02-21 16:20 UTC, wolfendale commented on test/integration/SDESServiceSpec.scala
> +      .configure(config)
Rather than parsing a config string we can just do
```scala
.configure(
  "microservice.services.sdes.host" -> host,
  "microservice.services.sdes.port" -> wiremockPort
)
```

Can see an example of using wiremock in tests [here](https://github.com/hmrc/tax-fraud-reporting-frontend/blob/main/it/services/AddressLookupServiceSpec.scala#L26-L28)

2022-02-21 16:52 UTC, kiran-hmrc commented on app/uk/gov/hmrc/taxfraudreporting/services/SDESService.scala
> +              s"Received a non 204 status from SDES when notified about file :: ${fileNotifyRequest.file.name}  with correlationId::${fileNotifyRequest.audit.correlationID}. Status: $status, body: ${
done

2022-02-21 16:53 UTC, kiran-hmrc commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +  private def notifySDES(correlationID: UUID, fileName: String, objWithSummary: ObjectSummaryWithMd5): Unit = {
I think given that it's a side-effect, we are already logging the error and tagging the reports in mongo on success, I'm not sure if we need to send it back as a future.

2022-02-21 16:53 UTC, kiran-hmrc commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +  private val objectStoreLocationPrefix: String = s"$fileLocationBaseUrl/object-store/object/ris-kana/"
done

2022-02-22 08:10 UTC, wolfendale commented on app/uk/gov/hmrc/taxfraudreporting/services/ObjectStorageWorker.scala
> +  private def notifySDES(correlationID: UUID, fileName: String, objWithSummary: ObjectSummaryWithMd5): Unit = {
By doing that errors within the worker will be inconsistent. Chaining our futures allows us to have a set escalation of errors throughout the code. Also, without passing back a future we won't be notified about a mongo failure on update. (There may be internal logging but it's unlikely we would see it)

2022-02-22 11:20 UTC, wolfendale approved these changes

2022-02-22 11:58 UTC, merged