DDCYLS-3251 - Encryption of data sent to mongo
hmrc/tax-fraud-reporting pull request #45
Opened 2023-07-26 08:13 UTC by dnyuar

2023-07-26 10:53 UTC, lewishay requested changes

2023-07-26 13:10 UTC, dnyuar commented on test/shared/GenDriven.scala
> +  val listsOfFraudReports: Gen[List[FraudReport]] = nonEmptyListsOf(fraudReports, 1)
This was a change that was made while trying out different things with the tests, I'll change it back now

2023-07-26 13:10 UTC, dnyuar commented on test/integration/FraudReportStreamerSpec.scala
> +    "include " in {
Yeah I agree, I'll make the changes now

2023-07-27 08:04 UTC, lewishay approved these changes

2023-07-27 08:05 UTC, merged